name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_linux:
    name: build-linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v2
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: pwd && tree -C -L 3
      - run: cargo build --verbose

  build_and_test_mac:
    name: build-mac
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v2
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose

  # TODO: Enable after windows build issues are resolved.
  # build_and_test_windows:
  #   name: build-and-test-windows
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       toolchain:
  #         - stable
  #         # - beta
  #         # - nightly
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
  #     - run: cargo build --verbose
  #     - run: cargo test --verbose
